algoritmo "comments"
const // constants
  n = 1 // value
tipo // types
  item = registro // record
    // fields
    value: inteiro // field
    // before record end
  fimregistro // record end
var
  x: item // variable
inicio
  se verdadeiro entao // condition
    // empty then
  senao // alternative
    // empty else
  fimse // conditional end
  escolha n // selector
    caso 1: // label
      // empty case
    outrocaso: // default
      // empty default
  fimescolha // choice end
fimalgoritmo
