algoritmo "comments"

// before procedure
procedimento P() // procedure
var // locals
  // empty locals
inicio // local body
  // before procedure end
fimprocedimento // procedure end

// before function
funcao F(): inteiro // function
inicio
  retorne 1 // result
fimfuncao // function end
// before main body
inicio
  enquanto falso faca // while
    // empty while
  fimenquanto // while end
  repita // repeat
    // empty repeat
  ate verdadeiro // repeat end
  para i de 1 ate 0 faca // for
    // empty for
  fimpara // for end
  P() // call
fimalgoritmo
