package main

import (
	"strings"
	"testing"
)

func TestReviewedExclusionArtifactHashes(t *testing.T) {
	t.Parallel()
	for _, mode := range []string{"evidence", "incremental", "implementation-acceptance"} {
		for _, name := range []string{"source.alg", "input.txt", "raw.txt", "output.txt", "screenshot.txt", "transcription.txt", "generated.txt"} {
			t.Run(mode+"/"+name, func(t *testing.T) {
				t.Parallel()
				root, m := testManifest(t)
				writeArtifact(t, root, "review.md", "Only finite completion is excluded; original evidence remains required.\n")
				r := &review{Reason: "Reviewed external-stop exclusion", Link: "review.md"}
				e := &m.Probes[0].Evidence
				e.State, e.Review = "not-applicable", r
				screenshot := writeArtifact(t, root, "probes/output/screenshot.txt", "Synthetic image bytes.\n")
				transcription := writeArtifact(t, root, "probes/output/transcription.txt", "Synthetic transcription.\n")
				generated := writeArtifact(t, root, "probes/output/generated.txt", "Generated bytes.\n")
				e.Screenshot, e.Transcription = &screenshot, &transcription
				e.Generated = []generatedFile{{Path: "result.dat", Content: generated}}
				m.Probes[0].Implementation.State = "not-applicable"
				m.Probes[0].Implementation.Review = r
				if err := validate(root, m, mode, nil); err != nil {
					t.Fatal(err)
				}
				writeArtifact(t, root, "probes/output/"+name, "altered")
				if err := validate(root, m, mode, nil); err == nil || !strings.Contains(err.Error(), "hash mismatch") {
					t.Fatalf("error = %v, want retained artifact hash mismatch", err)
				}
			})
		}
	}
}

func TestReviewedExclusionGeneratedPaths(t *testing.T) {
	t.Parallel()
	for _, mode := range []string{"evidence", "incremental", "implementation-acceptance"} {
		for _, tt := range []struct{ name, path, want string }{
			{"safe", "result.dat", ""},
			{"unsafe", "../result.dat", "unsafe path"},
			{"duplicate", "result.dat", "duplicate generated reference path"},
		} {
			t.Run(mode+"/"+tt.name, func(t *testing.T) {
				t.Parallel()
				root, m := testManifest(t)
				writeArtifact(t, root, "review.md", "Reviewed exclusion retaining generated evidence.\n")
				r := &review{Reason: "Reviewed external-stop exclusion", Link: "review.md"}
				e := &m.Probes[0].Evidence
				e.State, e.Review = "not-applicable", r
				a := writeArtifact(t, root, "generated.txt", "Generated bytes.\n")
				e.Generated = []generatedFile{{Path: tt.path, Content: a}}
				if tt.name == "duplicate" {
					e.Generated = append(e.Generated, e.Generated[0])
				}
				m.Probes[0].Implementation.State = "not-applicable"
				m.Probes[0].Implementation.Review = r
				err := validate(root, m, mode, nil)
				if tt.want == "" && err != nil {
					t.Fatal(err)
				}
				if tt.want != "" && (err == nil || !strings.Contains(err.Error(), tt.want)) {
					t.Fatalf("error = %v, want %q", err, tt.want)
				}
			})
		}
	}
}
