package main

import (
	"strings"
	"testing"
)

func TestReviewedExclusionArtifactHashes(t *testing.T) {
	t.Parallel()
	for _, mode := range []string{"evidence", "incremental", "implementation-acceptance"} {
		for _, name := range []string{"source.alg", "input.txt", "raw.txt", "output.txt", "screenshot.txt", "transcription.txt", "generated.txt"} {
			t.Run(mode+"/"+name, func(t *testing.T) {
				t.Parallel()
				root, m := testManifest(t)
				writeArtifact(t, root, "review.md", "Only finite completion is excluded; original evidence remains required.\n")
				r := &review{Reason: "Reviewed external-stop exclusion", Link: "review.md"}
				e := &m.Probes[0].Evidence
				e.State, e.Review = "not-applicable", r
				screenshot := writeArtifact(t, root, "probes/output/screenshot.txt", "Synthetic image bytes.\n")
				transcription := writeArtifact(t, root, "probes/output/transcription.txt", "Synthetic transcription.\n")
				generated := writeArtifact(t, root, "probes/output/generated.txt", "Generated bytes.\n")
				e.Screenshot, e.Transcription = &screenshot, &transcription
				e.Generated = []generatedFile{{Path: "result.dat", Content: generated}}
				m.Probes[0].Implementation.State = "not-applicable"
				m.Probes[0].Implementation.Review = r
				if err := validate(root, m, mode, nil); err != nil {
					t.Fatal(err)
				}
				writeArtifact(t, root, "probes/output/"+name, "altered")
				if err := validate(root, m, mode, nil); err == nil || !strings.Contains(err.Error(), "hash mismatch") {
					t.Fatalf("error = %v, want retained artifact hash mismatch", err)
				}
			})
		}
	}
}

func TestReviewedExclusionGeneratedPaths(t *testing.T) {
	t.Parallel()
	for _, mode := range []string{"evidence", "incremental", "implementation-acceptance"} {
		for _, tt := range []struct{ name, path, want string }{
			{"safe", "result.dat", ""},
			{"unsafe", "../result.dat", "unsafe path"},
			{"duplicate", "result.dat", "duplicate generated reference path"},
			{"file period", "result.dat.", "unsafe path"},
			{"file space", "result.dat ", "unsafe path"},
			{"directory period", "data./result.dat", "unsafe path"},
			{"directory space", "data /result.dat", "unsafe path"},
		} {
			t.Run(mode+"/"+tt.name, func(t *testing.T) {
				t.Parallel()
				root, m := testManifest(t)
				writeArtifact(t, root, "review.md", "Reviewed exclusion retaining generated evidence.\n")
				r := &review{Reason: "Reviewed external-stop exclusion", Link: "review.md"}
				e := &m.Probes[0].Evidence
				e.State, e.Review = "not-applicable", r
				a := writeArtifact(t, root, "generated.txt", "Generated bytes.\n")
				e.Generated = []generatedFile{{Path: tt.path, Content: a}}
				if tt.name == "duplicate" {
					e.Generated = append(e.Generated, e.Generated[0])
				}
				m.Probes[0].Implementation.State = "not-applicable"
				m.Probes[0].Implementation.Review = r
				err := validate(root, m, mode, nil)
				if tt.want == "" && err != nil {
					t.Fatal(err)
				}
				if tt.want != "" && (err == nil || !strings.Contains(err.Error(), tt.want)) {
					t.Fatalf("error = %v, want %q", err, tt.want)
				}
			})
		}
	}
}

func TestReviewedExclusionFileLayouts(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name                                string
		inputs, generated, expected, absent []string
		want                                string
	}{
		{name: "input parent", inputs: []string{"data"}, generated: []string{"data/output.dat"}, want: "file path is both file and directory"},
		{name: "input child", inputs: []string{"data/input.dat"}, generated: []string{"data"}, want: "file path is both file and directory"},
		{name: "deep input parent", inputs: []string{"data"}, generated: []string{"data/nested/output.dat"}, want: "file path is both file and directory"},
		{name: "generated parent first", generated: []string{"data", "data/output.dat"}, want: "file path is both file and directory"},
		{name: "generated child first", generated: []string{"data/output.dat", "data"}, want: "file path is both file and directory"},
		{name: "absent parent", generated: []string{"data/output.dat"}, absent: []string{"data"}, want: "absent path"},
		{name: "absent child", generated: []string{"data"}, absent: []string{"data/output.dat"}, want: "absent path"},
		{name: "generated case aliases", generated: []string{"result.dat", "RESULT.DAT"}, want: "case-insensitive path collision"},
		{name: "directory case aliases", inputs: []string{"Data/input.dat"}, generated: []string{"data/output.dat"}, want: "case-insensitive path collision"},
		{name: "retained output only", generated: []string{"data/output.dat"}},
		{name: "shared directory", inputs: []string{"data/input.dat"}, generated: []string{"data/output.dat"}},
		{name: "similar prefix", inputs: []string{"data"}, generated: []string{"database/output.dat"}},
		{name: "separate layouts", generated: []string{"data"}, expected: []string{"data/output.dat"}},
		{name: "input removal", inputs: []string{"input.dat"}, absent: []string{"input.dat"}},
		{name: "empty layout"},
	}
	for _, mode := range []string{"evidence", "incremental", "implementation-acceptance"} {
		for _, tt := range tests {
			t.Run(mode+"/"+tt.name, func(t *testing.T) {
				t.Parallel()
				root, m := testManifest(t)
				writeArtifact(t, root, "review.md", "Reviewed exclusion retaining original file observations.\n")
				r := &review{Reason: "Reviewed external-stop exclusion", Link: "review.md"}
				p := &m.Probes[0]
				p.Evidence.State, p.Evidence.Review = "not-applicable", r
				p.Implementation.State, p.Implementation.Review = "not-applicable", r
				content := writeArtifact(t, root, "fixture.txt", "Fixture bytes.\n")
				for _, name := range tt.inputs {
					p.Files = append(p.Files, generatedFile{Path: name, Content: content})
				}
				for _, name := range tt.generated {
					p.Evidence.Generated = append(p.Evidence.Generated, generatedFile{Path: name, Content: content})
				}
				for _, name := range tt.expected {
					p.Implementation.Expected.Generated = append(p.Implementation.Expected.Generated, generatedFile{Path: name, Content: content})
				}
				p.Evidence.Absent = tt.absent
				err := validate(root, m, mode, nil)
				if tt.want == "" {
					if err != nil {
						t.Fatal(err)
					}
				} else if err == nil || !strings.Contains(err.Error(), tt.want) {
					t.Fatalf("error = %v, want %q", err, tt.want)
				}
			})
		}
	}
}
