algoritmo "precision boundaries"
inicio
escreval("|",1.5:10:14,"|")
escreval("|",1.5:10:15,"|")
escreval("|",1.5:10:16,"|")
escreval("|",1.5:10:17,"|")
escreval("|",1.5:10:30,"|")
escreval("|",1.5:10:200,"|")
escreval("|",1.5:10:214,"|")
escreval("|",1.5:10:215,"|")
escreval("|",1.5:10:216,"|")
escreval("|",1.5:10:217,"|")
escreval("|",1.5:10:218,"|")
escreval("|",1.5:10:255,"|")
escreval("|",1.5:10:256,"|")
escreval("|",1.5:10:260,"|")
escreval("|",1.5:10:512,"|")
fimalgoritmo
