algoritmo "format value identity"
inicio
escreval(numpcarac(caracpnum("0.000000000000000006")))
escreval("|",caracpnum("0.000000000000000006"):10:30,"|")
escreval(numpcarac(caracpnum("6e-18")))
escreval("|",caracpnum("6e-18"):10:30,"|")
escreval(numpcarac(caracpnum("0.000000000000000009")))
escreval("|",caracpnum("0.000000000000000009"):10:30,"|")
escreval(numpcarac(caracpnum("9e-18")))
escreval("|",caracpnum("9e-18"):10:30,"|")
escreval(numpcarac(caracpnum("0.000000000000000005")))
escreval("|",caracpnum("0.000000000000000005"):10:30,"|")
escreval(numpcarac(caracpnum("5e-18")))
escreval("|",caracpnum("5e-18"):10:30,"|")
fimalgoritmo
