algoritmo "output-edges"
inicio
  escreval("BEGIN:output-edges")
  escreval("N=[", -1, "][", -1.5, "]")
  escreval("Z=[", 0, "][", 0.0, "]")
  escreval("W0=[", 1:0, "][", 1.5:0, "]")
  escreval("W1=[", 123:1, "][", 1.5:1, "]")
  escreval("W5=[", -1:5, "][", -1.5:5, "]")
  escreval("D=[", 1.5:0:2, "][", -1.5:0:2, "]")
  escreval("I=[", 1:0:2, "][", 123:1:2, "]")
  escreval("S=[", "x":3, "][", verdadeiro, "][", falso, "]")
  escreval("END:output-edges")
fimalgoritmo
