algoritmo "format value identity"
inicio
escreval(numpcarac(1e36))
escreval("|",1e36:10:2,"|")
escreval(numpcarac(1.000000000000001e36))
escreval("|",1.000000000000001e36:10:2,"|")
escreval(numpcarac(1.01e36))
escreval("|",1.01e36:10:2,"|")
escreval(numpcarac(1.1e36))
escreval("|",1.1e36:10:2,"|")
escreval(numpcarac(2e36))
escreval("|",2e36:10:2,"|")
escreval(numpcarac(-1e36))
escreval("|",-1e36:10:2,"|")
fimalgoritmo
