algoritmo "documented functions"
var
value: real
inicio
escreval("ABS=",abs(-7))
escreval("ARCCOS=",arccos(1))
escreval("ARCSEN=",arcsen(0))
escreval("ARCTAN=",arctan(0))
escreval("COS=",cos(0))
value <- cotan(1)
escreval("COTAN=",(value >= 0) e (value < 2))
escreval("EXP=",exp(2,3))
escreval("GRAUPRAD=",grauprad(0))
escreval("INT=",int(2.9))
escreval("LOG=",log(1))
escreval("LOGN=",logn(1))
value <- pi
escreval("PI=",(value >= 3) e (value < 4))
escreval("QUAD=",quad(2))
escreval("RADPGRAU=",radpgrau(0))
escreval("RAIZQ=",raizq(4))
value <- rand
escreval("RAND=",(value >= 0) e (value < 1))
escreval("RANDI=",randi(1))
escreval("SEN=",sen(0))
escreval("TAN=",tan(0))
escreval("ASC=",asc("A"))
escreval("CARAC=",carac(65))
escreval("CARACPNUM=",caracpnum("7"))
escreval("COMPR=",compr("ABC"))
escreval("COPIA=",copia("ABC",2,1))
escreval("MAIUSC=",maiusc("abc"))
escreval("MINUSC=",minusc("ABC"))
escreval("NUMPCARAC=",numpcarac(7))
escreval("POS=",pos("B","ABC"))
fimalgoritmo
