algoritmo "fraction conversion"
inicio
escreval(numpcarac(caracpnum("-0.0")))
escreval("|",caracpnum("-0.0"):10:30,"|")
escreval(numpcarac(caracpnum("+0.0")))
escreval("|",caracpnum("+0.0"):10:30,"|")
escreval(numpcarac(caracpnum("000.0")))
escreval("|",caracpnum("000.0"):10:30,"|")
escreval(numpcarac(caracpnum("-000.0")))
escreval("|",caracpnum("-000.0"):10:30,"|")
escreval(numpcarac(caracpnum("0e-18")))
escreval("|",caracpnum("0e-18"):10:30,"|")
escreval(numpcarac(caracpnum("-0e-18")))
escreval("|",caracpnum("-0e-18"):10:30,"|")
escreval(numpcarac(caracpnum("0006e-18")))
escreval("|",caracpnum("0006e-18"):10:30,"|")
fimalgoritmo
